# Generated by Django 4.0.4 on 2022-07-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0002_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='gmail',
            field=models.EmailField(max_length=254),
        ),
    ]
